### ISSUE TITLE
Convert RdfMigrator to be a job invoked via Main program

### ISSUE THREAD

**Issue by rjrudin** [sastafford/marklogic-spring-batch#75] opened 2016-06-07 12:27 UTC
Just like SqlMigrator, RdfMigrator can become a job config that is then invoked via Main.

Can then remove commons-cli from the set of dependencies for core.

**Comment by sastafford** [comment] 2016-06-07 14:12
Duplicate of #68, Intent of #68 is the same as this.  Close as duplicate.  Will copy this info to #68.

**Closed by sastafford** 2016-06-07 14:12 UTC
Labels: job
